#pragma once

#include <SDL.h>
#include <SDL_ttf.h>
#include <SDL_image.h>

#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <filesystem>
#include <optional>
#include <utility>
#include <stdlib.h>
#include <cmath>
#include <math.h>
#include <algorithm>
#include <array>
#include <string>
#include <string_view>
#include <unordered_map>
#include <map>
#include <set>
#include <vector>
#include <queue>
#include <memory>
#include <stdexcept>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <thread>

#include "GameTime.h"
#include "GeneralTimer.h"
#include "ValuesRange.h"
#include "Calculator.h"
#include "Texture.h"
#include "TextureLoader.h"
#include "Position.h"
#include "Drawable.h"
#include "DrawableBoardEntity.h"
#include "Logger.h"