#pragma once
enum class PlayerActionTypes {
	NONE=-1,
	OPEN_EQUIPMENT,
	MOVE_UP,
	MOVE_LEFT,
	MOVE_DOWN,
	MOVE_RIGHT,
	MOVE_CAMERA_UP,
	MOVE_CAMERA_LEFT,
	MOVE_CAMERA_DOWN,
	MOVE_CAMERA_RIGHT,
	COUNT
};